name: ⛔️ ❓ Question
description: Ask a question
title: "My Question"
body:
- type: markdown
  attributes:
    value: |
      > [!NOTE]
      > Issues are not the preferred way to raise questions or have discussions.
      > 
      > Please ensure you have exhausted all the alternatives before creating an issue for a question.
- type: checkboxes
  attributes:
    label: Have you checked if the product documentation answers your question?
    description: Check the Repository details and README for a link to product documentation.
    options:
    - label: I have searched the product documentation
      required: true
- type: checkboxes
  attributes:
    label: Can you post a question in Discussions instead?
    description: If you can see the Discussions tab for this repository, please post questions in a relevant Q & A category.
    options:
    - label: This repository does not have public Discussions
      required: true
- type: checkboxes
  attributes:
    label: Does this product have associated project drop-in sessions?
    description: Check the Repository README to see if there are drop-in sessions where you can ask questions.
    options:
    - label: This product does not advertise drop-in sessions.
      required: true
- type: checkboxes
  attributes:
    label: Does the README outline a preferred way to ask questions?
    description: Check the Repository README for the preferred way to submit questions.
    options:
    - label: I have checked the README and found no alternative approach to ask my question.
      required: true
- type: textarea
  attributes:
    label: What is your question?
    description: A concise description of your question.
  validations:
    required: false
- type: input
  attributes:
    label: I'm part of a Project Team
    description: |
      If you work in a team that is using this product, or collaborating with us to build it, let us know who you are.
      
      You can leave this blank if it doesn't apply.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
